### ISSUE TITLE
Using the provided example produces an error

### ISSUE THREAD

**Issue by thedrow** [pocesar/node-packet-frame#2]
I'm trying to create a TCP server that listens to a protobuf socket from hekad.
The example produces the following error from https://github.com/pocesar/node-protosocket/blob/master/lib/libs.js#L112

I'm not sure what function you expect it to be.

**Comment by ddlsmurf** [comment]
If you don't mind, could you explain that this does not work in your readme ? just lost some time trying to figure it out =/

**Comment by pocesar** [comment]
sure, sorry about that @ddlsmurf

**Comment by ddlsmurf** [comment]
thanks!
